const nodeGlobals = Object.fromEntries(
  [
    "AbortController",
    "AbortSignal",
    "Array",
    "ArrayBuffer",
    "BigInt",
    "Blob",
    "Buffer",
    "clearImmediate",
    "clearInterval",
    "clearTimeout",
    "console",
    "Date",
    "Error",
    "EventSource",
    "fetch",
    "FormData",
    "globalThis",
    "Headers",
    "Infinity",
    "isFinite",
    "isNaN",
    "JSON",
    "Map",
    "Math",
    "NaN",
    "Number",
    "Object",
    "performance",
    "Promise",
    "queueMicrotask",
    "ReadableStream",
    "RegExp",
    "Request",
    "Response",
    "Set",
    "setImmediate",
    "setInterval",
    "setTimeout",
    "String",
    "structuredClone",
    "Symbol",
    "TextDecoder",
    "TextEncoder",
    "TransformStream",
    "URL",
    "URLSearchParams",
    "undefined",
    "WeakMap",
    "WeakSet",
    "WebSocket",
  ].map((name) => [name.trim(), "readonly"]),
);

export default [
  {
    ignores: ["node_modules/**", ".test-run/**"],
  },
  {
    files: ["**/*.js", "**/*.mjs", "**/*.cjs"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: nodeGlobals,
    },
    rules: {
      "no-constant-condition": ["error", { checkLoops: false }],
      "no-dupe-args": "error",
      "no-dupe-keys": "error",
      "no-duplicate-case": "error",
      "no-func-assign": "error",
      "no-import-assign": "error",
      "no-redeclare": "error",
      "no-self-assign": "error",
      "no-unreachable": "error",
    },
  },
];
